/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum Overflow {
  Constrain = 'Constrain',
  Reject = 'Reject'
}
export const enum Disambiguation {
  Compatible = 'Compatible',
  Earlier = 'Earlier',
  Later = 'Later',
  Reject = 'Reject'
}
export const enum OffsetDisambiguation {
  Use = 'Use',
  Prefer = 'Prefer',
  Ignore = 'Ignore',
  Reject = 'Reject'
}
export const enum RoundingMode {
  Ceil = 'Ceil',
  Floor = 'Floor',
  Expand = 'Expand',
  Trunc = 'Trunc',
  HalfCeil = 'HalfCeil',
  HalfFloor = 'HalfFloor',
  HalfExpand = 'HalfExpand',
  HalfTrunc = 'HalfTrunc',
  HalfEven = 'HalfEven'
}
export const enum Unit {
  Auto = 'Auto',
  Nanosecond = 'Nanosecond',
  Microsecond = 'Microsecond',
  Millisecond = 'Millisecond',
  Second = 'Second',
  Minute = 'Minute',
  Hour = 'Hour',
  Day = 'Day',
  Week = 'Week',
  Month = 'Month',
  Year = 'Year'
}
export const enum DisplayCalendar {
  Auto = 'Auto',
  Always = 'Always',
  Never = 'Never',
  Critical = 'Critical'
}
export const enum DisplayOffset {
  Auto = 'Auto',
  Never = 'Never'
}
export const enum DisplayTimeZone {
  Auto = 'Auto',
  Never = 'Never',
  Critical = 'Critical'
}
export interface DifferenceSettings {
  largestUnit?: Unit
  smallestUnit?: Unit
  roundingMode?: RoundingMode
  roundingIncrement?: number
}
export interface RoundingOptions {
  largestUnit?: Unit
  smallestUnit?: Unit
  roundingMode?: RoundingMode
  roundingIncrement?: number
}
export interface ToStringRoundingOptions {
  precision?: number
  isMinute?: boolean
  smallestUnit?: Unit
  roundingMode?: RoundingMode
}
export declare function nowInstant(): Instant
export declare function nowTimeZone(): TimeZone
export declare function nowZonedDateTimeIso(timeZone?: TimeZone | undefined | null): ZonedDateTime
export declare function nowPlainDateTimeIso(timeZone?: TimeZone | undefined | null): PlainDateTime
export declare function nowPlainDateIso(timeZone?: TimeZone | undefined | null): PlainDate
export declare function nowPlainTimeIso(timeZone?: TimeZone | undefined | null): PlainTime
export declare class Calendar {
  /** Creates a new Calendar from a calendar identifier string (e.g. "iso8601", "gregorian", "japanese"). */
  constructor(id: string)
  /** Create an ISO 8601 calendar. */
  static iso(): Calendar
  /** Create a Gregorian calendar. */
  static gregorian(): Calendar
  /** Create a Japanese calendar. */
  static japanese(): Calendar
  /** Create a Buddhist calendar. */
  static buddhist(): Calendar
  /** Create a Chinese calendar. */
  static chinese(): Calendar
  /** Create a Coptic calendar. */
  static coptic(): Calendar
  /** Create a Dangi (Korean) calendar. */
  static dangi(): Calendar
  /** Create an Ethiopian calendar. */
  static ethiopian(): Calendar
  /** Create an Ethiopian Amete Alem calendar. */
  static ethiopianAmeteAlem(): Calendar
  /** Create a Hebrew calendar. */
  static hebrew(): Calendar
  /** Create an Indian calendar. */
  static indian(): Calendar
  /** Create a Hijri Tabular (Friday epoch) calendar. */
  static hijriTabularFriday(): Calendar
  /** Create a Hijri Tabular (Thursday epoch) calendar. */
  static hijriTabularThursday(): Calendar
  /** Create a Hijri Umm al-Qura calendar. */
  static hijriUmmAlQura(): Calendar
  /** Create a Persian calendar. */
  static persian(): Calendar
  /** Create a Republic of China (Minguo) calendar. */
  static roc(): Calendar
  get id(): string
  get isIso(): boolean
  toString(): string
}
export declare class TimeZone {
  /**
   * Constructor: takes IANA timezone identifier or UTC offset string
   * (e.g. "America/New_York", "+05:30", "UTC")
   */
  constructor(identifier: string)
  /** Factory for UTC */
  static utc(): TimeZone
  /** Get the timezone identifier string */
  get id(): string
  toString(): string
}
export declare class PlainDate {
  /** Construct from ISO year, month, day, and optional calendar. */
  constructor(year: number, month: number, day: number, calendar?: Calendar | undefined | null)
  static from(s: string): PlainDate
  get year(): number
  get month(): number
  get monthCode(): string
  get day(): number
  get dayOfWeek(): number
  get dayOfYear(): number
  get weekOfYear(): number | null
  get yearOfWeek(): number | null
  get daysInWeek(): number
  get daysInMonth(): number
  get daysInYear(): number
  get monthsInYear(): number
  get inLeapYear(): boolean
  get era(): string | null
  get eraYear(): number | null
  get calendar(): Calendar
  add(duration: Duration, overflow?: Overflow | undefined | null): PlainDate
  subtract(duration: Duration, overflow?: Overflow | undefined | null): PlainDate
  until(other: PlainDate, settings?: DifferenceSettings | undefined | null): Duration
  since(other: PlainDate, settings?: DifferenceSettings | undefined | null): Duration
  equals(other: PlainDate): boolean
  static compare(one: PlainDate, two: PlainDate): number
  toString(displayCalendar?: DisplayCalendar | undefined | null): string
  withCalendar(calendar: Calendar): PlainDate
  toJson(): string
  valueOf(): void
}
export declare class PlainTime {
  constructor(hour: number, minute: number, second: number, millisecond?: number | undefined | null, microsecond?: number | undefined | null, nanosecond?: number | undefined | null)
  static from(s: string): PlainTime
  get hour(): number
  get minute(): number
  get second(): number
  get millisecond(): number
  get microsecond(): number
  get nanosecond(): number
  add(duration: Duration): PlainTime
  subtract(duration: Duration): PlainTime
  until(other: PlainTime, settings?: DifferenceSettings | undefined | null): Duration
  since(other: PlainTime, settings?: DifferenceSettings | undefined | null): Duration
  round(options: RoundingOptions): PlainTime
  static compare(one: PlainTime, two: PlainTime): number
  equals(other: PlainTime): boolean
  toString(options?: ToStringRoundingOptions | undefined | null): string
  toJson(): string
  valueOf(): void
}
export declare class PlainDateTime {
  constructor(year: number, month: number, day: number, hour?: number | undefined | null, minute?: number | undefined | null, second?: number | undefined | null, millisecond?: number | undefined | null, microsecond?: number | undefined | null, nanosecond?: number | undefined | null, calendar?: Calendar | undefined | null)
  static from(s: string): PlainDateTime
  get year(): number
  get month(): number
  get monthCode(): string
  get day(): number
  get dayOfWeek(): number
  get dayOfYear(): number
  get weekOfYear(): number | null
  get yearOfWeek(): number | null
  get daysInWeek(): number
  get daysInMonth(): number
  get daysInYear(): number
  get monthsInYear(): number
  get inLeapYear(): boolean
  get era(): string | null
  get eraYear(): number | null
  get calendar(): Calendar
  get hour(): number
  get minute(): number
  get second(): number
  get millisecond(): number
  get microsecond(): number
  get nanosecond(): number
  add(duration: Duration, overflow?: Overflow | undefined | null): PlainDateTime
  subtract(duration: Duration, overflow?: Overflow | undefined | null): PlainDateTime
  until(other: PlainDateTime, settings?: DifferenceSettings | undefined | null): Duration
  since(other: PlainDateTime, settings?: DifferenceSettings | undefined | null): Duration
  round(options: RoundingOptions): PlainDateTime
  equals(other: PlainDateTime): boolean
  static compare(one: PlainDateTime, two: PlainDateTime): number
  toPlainDate(): PlainDate
  toPlainTime(): PlainTime
  withCalendar(calendar: Calendar): PlainDateTime
  toString(options?: ToStringRoundingOptions | undefined | null, displayCalendar?: DisplayCalendar | undefined | null): string
  toJson(): string
  valueOf(): void
}
export declare class ZonedDateTime {
  /** Construct from epoch nanoseconds (BigInt), timezone, and optional calendar. */
  constructor(epochNanoseconds: bigint, timezone: TimeZone, calendar?: Calendar | undefined | null)
  /** Parse from an IXDTF string. */
  static from(s: string): ZonedDateTime
  static fromEpochMilliseconds(ms: number, timezone: TimeZone, calendar?: Calendar | undefined | null): ZonedDateTime
  get year(): number
  get month(): number
  get monthCode(): string
  get day(): number
  get dayOfWeek(): number
  get dayOfYear(): number
  get weekOfYear(): number | null
  get yearOfWeek(): number | null
  get daysInWeek(): number
  get daysInMonth(): number
  get daysInYear(): number
  get monthsInYear(): number
  get inLeapYear(): boolean
  get era(): string | null
  get eraYear(): number | null
  get hour(): number
  get minute(): number
  get second(): number
  get millisecond(): number
  get microsecond(): number
  get nanosecond(): number
  get calendar(): Calendar
  get timeZone(): TimeZone
  get offset(): string
  get offsetNanoseconds(): number
  get epochMilliseconds(): number
  get epochNanoseconds(): bigint
  add(duration: Duration, overflow?: Overflow | undefined | null): ZonedDateTime
  subtract(duration: Duration, overflow?: Overflow | undefined | null): ZonedDateTime
  until(other: ZonedDateTime, settings?: DifferenceSettings | undefined | null): Duration
  since(other: ZonedDateTime, settings?: DifferenceSettings | undefined | null): Duration
  round(options: RoundingOptions): ZonedDateTime
  equals(other: ZonedDateTime): boolean
  static compareInstant(one: ZonedDateTime, two: ZonedDateTime): number
  get hoursInDay(): number
  startOfDay(): ZonedDateTime
  toInstant(): Instant
  toPlainDate(): PlainDate
  toPlainTime(): PlainTime
  toPlainDateTime(): PlainDateTime
  withCalendar(calendar: Calendar): ZonedDateTime
  withTimeZone(timezone: TimeZone): ZonedDateTime
  toString(options?: ToStringRoundingOptions | undefined | null): string
  toJson(): string
  valueOf(): void
}
export declare class Instant {
  /** Construct from epoch nanoseconds as BigInt. */
  constructor(epochNanoseconds: bigint)
  /** Parse from an ISO 8601 string. */
  static from(s: string): Instant
  /** Construct from epoch milliseconds. */
  static fromEpochMilliseconds(ms: number): Instant
  get epochMilliseconds(): number
  get epochNanoseconds(): bigint
  add(duration: Duration): Instant
  subtract(duration: Duration): Instant
  until(other: Instant, settings?: DifferenceSettings | undefined | null): Duration
  since(other: Instant, settings?: DifferenceSettings | undefined | null): Duration
  round(options: RoundingOptions): Instant
  equals(other: Instant): boolean
  static compare(one: Instant, two: Instant): number
  toString(options?: ToStringRoundingOptions | undefined | null): string
  toJson(): string
  valueOf(): void
}
export declare class Duration {
  /**
   * Construct with individual date/time components (all optional, default 0).
   *
   * Accepts f64 for all fields (matching JS Number type).
   * Microseconds and nanoseconds are converted to i128 to preserve
   * precision for values exceeding i64 range.
   */
  constructor(years?: number | undefined | null, months?: number | undefined | null, weeks?: number | undefined | null, days?: number | undefined | null, hours?: number | undefined | null, minutes?: number | undefined | null, seconds?: number | undefined | null, milliseconds?: number | undefined | null, microseconds?: number | undefined | null, nanoseconds?: number | undefined | null)
  static from(s: string): Duration
  get years(): number
  get months(): number
  get weeks(): number
  get days(): number
  get hours(): number
  get minutes(): number
  get seconds(): number
  get milliseconds(): number
  /** Note: returns f64 per TC39 Temporal spec. Precision loss possible for values > 2^53. */
  get microseconds(): number
  /** Note: returns f64 per TC39 Temporal spec. Precision loss possible for values > 2^53. */
  get nanoseconds(): number
  get sign(): number
  get isZero(): boolean
  negated(): Duration
  abs(): Duration
  add(other: Duration): Duration
  subtract(other: Duration): Duration
  round(options: RoundingOptions, relativeToDate?: PlainDate | undefined | null, relativeToZdt?: ZonedDateTime | undefined | null): Duration
  total(unit: Unit, relativeToDate?: PlainDate | undefined | null, relativeToZdt?: ZonedDateTime | undefined | null): number
  static compare(one: Duration, two: Duration, relativeToDate?: PlainDate | undefined | null, relativeToZdt?: ZonedDateTime | undefined | null): number
  toString(): string
  toJson(): string
  valueOf(): void
}
export declare class PlainYearMonth {
  constructor(year: number, month: number, calendar?: Calendar | undefined | null, referenceDay?: number | undefined | null)
  static from(s: string): PlainYearMonth
  get year(): number
  get month(): number
  get monthCode(): string
  get era(): string | null
  get eraYear(): number | null
  get daysInYear(): number
  get daysInMonth(): number
  get monthsInYear(): number
  get inLeapYear(): boolean
  get calendar(): Calendar
  add(duration: Duration, overflow?: Overflow | undefined | null): PlainYearMonth
  subtract(duration: Duration, overflow?: Overflow | undefined | null): PlainYearMonth
  until(other: PlainYearMonth, settings?: DifferenceSettings | undefined | null): Duration
  since(other: PlainYearMonth, settings?: DifferenceSettings | undefined | null): Duration
  equals(other: PlainYearMonth): boolean
  static compare(one: PlainYearMonth, two: PlainYearMonth): number
  toString(displayCalendar?: DisplayCalendar | undefined | null): string
  toJson(): string
  valueOf(): void
}
export declare class PlainMonthDay {
  constructor(month: number, day: number, calendar?: Calendar | undefined | null, referenceYear?: number | undefined | null)
  static from(s: string): PlainMonthDay
  get monthCode(): string
  get day(): number
  get calendar(): Calendar
  equals(other: PlainMonthDay): boolean
  toString(displayCalendar?: DisplayCalendar | undefined | null): string
  toJson(): string
  valueOf(): void
}
