/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'temporal_rs.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./temporal_rs.android-arm64.node')
          } else {
            nativeBinding = require('temporal_rs-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'temporal_rs.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./temporal_rs.android-arm-eabi.node')
          } else {
            nativeBinding = require('temporal_rs-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'temporal_rs.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./temporal_rs.win32-x64-msvc.node')
          } else {
            nativeBinding = require('temporal_rs-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'temporal_rs.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./temporal_rs.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('temporal_rs-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'temporal_rs.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./temporal_rs.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('temporal_rs-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'temporal_rs.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./temporal_rs.darwin-universal.node')
      } else {
        nativeBinding = require('temporal_rs-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'temporal_rs.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./temporal_rs.darwin-x64.node')
          } else {
            nativeBinding = require('temporal_rs-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'temporal_rs.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./temporal_rs.darwin-arm64.node')
          } else {
            nativeBinding = require('temporal_rs-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'temporal_rs.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./temporal_rs.freebsd-x64.node')
      } else {
        nativeBinding = require('temporal_rs-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'temporal_rs.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./temporal_rs.linux-x64-musl.node')
            } else {
              nativeBinding = require('temporal_rs-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'temporal_rs.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./temporal_rs.linux-x64-gnu.node')
            } else {
              nativeBinding = require('temporal_rs-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'temporal_rs.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./temporal_rs.linux-arm64-musl.node')
            } else {
              nativeBinding = require('temporal_rs-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'temporal_rs.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./temporal_rs.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('temporal_rs-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'temporal_rs.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./temporal_rs.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('temporal_rs-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'temporal_rs.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./temporal_rs.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('temporal_rs-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'temporal_rs.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./temporal_rs.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('temporal_rs-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'temporal_rs.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./temporal_rs.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('temporal_rs-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'temporal_rs.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./temporal_rs.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('temporal_rs-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { Overflow, Disambiguation, OffsetDisambiguation, RoundingMode, Unit, DisplayCalendar, DisplayOffset, DisplayTimeZone, Calendar, TimeZone, PlainDate, PlainTime, PlainDateTime, ZonedDateTime, Instant, Duration, PlainYearMonth, PlainMonthDay, nowInstant, nowTimeZone, nowZonedDateTimeIso, nowPlainDateTimeIso, nowPlainDateIso, nowPlainTimeIso } = nativeBinding

module.exports.Overflow = Overflow
module.exports.Disambiguation = Disambiguation
module.exports.OffsetDisambiguation = OffsetDisambiguation
module.exports.RoundingMode = RoundingMode
module.exports.Unit = Unit
module.exports.DisplayCalendar = DisplayCalendar
module.exports.DisplayOffset = DisplayOffset
module.exports.DisplayTimeZone = DisplayTimeZone
module.exports.Calendar = Calendar
module.exports.TimeZone = TimeZone
module.exports.PlainDate = PlainDate
module.exports.PlainTime = PlainTime
module.exports.PlainDateTime = PlainDateTime
module.exports.ZonedDateTime = ZonedDateTime
module.exports.Instant = Instant
module.exports.Duration = Duration
module.exports.PlainYearMonth = PlainYearMonth
module.exports.PlainMonthDay = PlainMonthDay
module.exports.nowInstant = nowInstant
module.exports.nowTimeZone = nowTimeZone
module.exports.nowZonedDateTimeIso = nowZonedDateTimeIso
module.exports.nowPlainDateTimeIso = nowPlainDateTimeIso
module.exports.nowPlainDateIso = nowPlainDateIso
module.exports.nowPlainTimeIso = nowPlainTimeIso
