// Type definitions for temporal_rs (ESM)
// This file re-exports all types from the CJS declaration file.
export {
  // Type aliases
  type CalendarLike,
  type DurationLike,
  type InstantLike,
  type PlainDateLike,
  type PlainDateTimeLike,
  type PlainMonthDayLike,
  type PlainTimeLike,
  type PlainYearMonthLike,
  type TimeZoneLike,
  type ZonedDateTimeLike,
  type PartialTemporalLike,
  // Like-object interfaces
  type DateLikeObject,
  type DateTimeLikeObject,
  type DurationLikeObject,
  type TimeLikeObject,
  type YearMonthLikeObject,
  type ZonedDateTimeLikeObject,
  // Unit types
  type DateUnit,
  type TimeUnit,
  type PluralizeUnit,
  // Options interfaces
  type DisambiguationOptions,
  type OverflowOptions,
  type TransitionOptions,
  type RoundingOptions,
  type RoundingOptionsWithLargestUnit,
  type ToStringRoundingOptions,
  type ToStringRoundingOptionsWithFractionalSeconds,
  type PlainDateToStringOptions,
  type PlainDateToZonedDateTimeOptions,
  type PlainTimeToStringOptions,
  type PlainDateTimeToStringOptions,
  type ZonedDateTimeToStringOptions,
  type ZonedDateTimeFromOptions,
  type DurationRelativeToOptions,
  type DurationRoundingOptions,
  type DurationToStringOptions,
  type DurationTotalOptions,
  type InstantToStringOptions,
  type PlainYearMonthToPlainDateOptions,
  type PlainMonthDayToPlainDateOptions,
  // Constructor interfaces
  type PlainDateConstructor,
  type PlainTimeConstructor,
  type PlainDateTimeConstructor,
  type ZonedDateTimeConstructor,
  type DurationConstructor,
  type InstantConstructor,
  type PlainYearMonthConstructor,
  type PlainMonthDayConstructor,
  type TemporalNow,
  type TemporalNamespace,
  // Values
  PlainDate,
  PlainTime,
  PlainDateTime,
  ZonedDateTime,
  Duration,
  Instant,
  PlainYearMonth,
  PlainMonthDay,
  Now,
  Temporal,
  Temporal as default,
} from "./temporal.js";
